/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Duration3 from './Duration3';

/**
* The Availability9 model module.
* @module model/Availability9
* @version 3900.6.0
*/
export default class Availability9 {
    /**
    * Constructs a new <code>Availability9</code>.
    * Settings controlling availability of the term to students.
    * @alias module:model/Availability9
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Availability9</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Availability9} obj Optional instance to populate.
    * @return {module:model/Availability9} The populated <code>Availability9</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Availability9();
                        
            
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = Duration3.constructFromObject(data['duration']);
            }
        }
        return obj;
    }

    /**
    * Whether the term and the courses it contains are available to students.  Instructors can always access their courses.   | Type      | Description  | --------- | --------- | | Yes | Students may access the term and the courses it contains. | | No | Students may not access the term or the courses it contains. | 
    * @member {module:model/Availability9.AvailableEnum} available
    */
    'available' = undefined;
    /**
    * @member {module:model/Duration3} duration
    */
    'duration' = undefined;



    /**
    * Allowed values for the <code>available</code> property.
    * @enum {String}
    * @readonly
    */
    static AvailableEnum = {
        /**
         * value: "Yes"
         * @const
         */
        "Yes": "Yes",
        /**
         * value: "No"
         * @const
         */
        "No": "No"    };

}
