/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Availability14 model module.
* @module model/Availability14
* @version 3900.6.0
*/
export default class Availability14 {
    /**
    * Constructs a new <code>Availability14</code>.
    * Settings controlling availability of the proctoring service.
    * @alias module:model/Availability14
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Availability14</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Availability14} obj Optional instance to populate.
    * @return {module:model/Availability14} The populated <code>Availability14</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Availability14();
                        
            
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'String');
            }
        }
        return obj;
    }

    /**
    * Whether the proctoring service is available within the system.   | Type      | Description  | --------- | --------- | | Yes |  | | No |  | 
    * @member {module:model/Availability14.AvailableEnum} available
    */
    'available' = undefined;



    /**
    * Allowed values for the <code>available</code> property.
    * @enum {String}
    * @readonly
    */
    static AvailableEnum = {
        /**
         * value: "Yes"
         * @const
         */
        "Yes": "Yes",
        /**
         * value: "No"
         * @const
         */
        "No": "No"    };

}
