/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Avatar model module.
* @module model/Avatar
* @version 3900.6.0
*/
export default class Avatar {
    /**
    * Constructs a new <code>Avatar</code>.
    * The user&#x27;s avatar metadata  **Since**: 3800.13.0
    * @alias module:model/Avatar
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Avatar</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Avatar} obj Optional instance to populate.
    * @return {module:model/Avatar} The populated <code>Avatar</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Avatar();
                        
            
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('uploadId')) {
                obj['uploadId'] = ApiClient.convertToType(data['uploadId'], 'String');
            }
        }
        return obj;
    }

    /**
    * The source of the user's avatar  **Since**: 3800.13.0   | Type      | Description  | --------- | --------- | | Default | The server default avatar | | User | The user set his/her own avatar | | System | A privileged user set the user's avatar to something other than default | 
    * @member {module:model/Avatar.SourceEnum} source
    */
    'source' = undefined;
    /**
    * The upload id of the avatar image file  **Since**: 3800.13.0
    * @member {String} uploadId
    */
    'uploadId' = undefined;



    /**
    * Allowed values for the <code>source</code> property.
    * @enum {String}
    * @readonly
    */
    static SourceEnum = {
        /**
         * value: "Default"
         * @const
         */
        "Default": "Default",
        /**
         * value: "User"
         * @const
         */
        "User": "User",
        /**
         * value: "System"
         * @const
         */
        "System": "System"    };

}
