/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body62 model module.
* @module model/Body62
* @version 3900.6.0
*/
export default class Body62 {
    /**
    * Constructs a new <code>Body62</code>.
    * @alias module:model/Body62
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body62</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body62} obj Optional instance to populate.
    * @return {module:model/Body62} The populated <code>Body62</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body62();
                        
            
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('feedback')) {
                obj['feedback'] = ApiClient.convertToType(data['feedback'], 'String');
            }
            if (data.hasOwnProperty('exempt')) {
                obj['exempt'] = ApiClient.convertToType(data['exempt'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * The text representation of this grade.
    * @member {String} text
    */
    'text' = undefined;
    /**
    * The score associated with this grade.
    * @member {Number} score
    */
    'score' = undefined;
    /**
    * The instructor notes associated with this grade. This notes field is used for grades on manual grade columns.   That is, when column.grading.type = Manual.  It is also used when column.grading.type = Attempts and the grade has been manually overridden.
    * @member {String} notes
    */
    'notes' = undefined;
    /**
    * The instructor feedback associated with this grade.  This feedback is used for grades on manual grade columns.   That is, when column.grading.type = Manual.  It is also used when column.grading.type = Attempts and the grade has been manually overridden.
    * @member {String} feedback
    */
    'feedback' = undefined;
    /**
    * Whether the score associated with this grade is ignored when computing the course grade.
    * @member {Boolean} exempt
    */
    'exempt' = undefined;




}
