/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body50 model module.
* @module model/Body50
* @version 3900.6.0
*/
export default class Body50 {
    /**
    * Constructs a new <code>Body50</code>.
    * @alias module:model/Body50
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body50</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body50} obj Optional instance to populate.
    * @return {module:model/Body50} The populated <code>Body50</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body50();
                        
            
            if (data.hasOwnProperty('isPrimary')) {
                obj['isPrimary'] = ApiClient.convertToType(data['isPrimary'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Whether or not this association represents the primary node association of the course
    * @member {Boolean} isPrimary
    */
    'isPrimary' = undefined;




}
