/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CopyV2 from './CopyV2';
import TargetCourseV2 from './TargetCourseV2';

/**
* The Body42 model module.
* @module model/Body42
* @version 3900.6.0
*/
export default class Body42 {
    /**
    * Constructs a new <code>Body42</code>.
    * @alias module:model/Body42
    * @class
    * @param targetCourse {module:model/TargetCourseV2} 
    */

    constructor(targetCourse) {
        
        
        this['targetCourse'] = targetCourse;
        
    }

    /**
    * Constructs a <code>Body42</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body42} obj Optional instance to populate.
    * @return {module:model/Body42} The populated <code>Body42</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body42();
                        
            
            if (data.hasOwnProperty('targetCourse')) {
                obj['targetCourse'] = TargetCourseV2.constructFromObject(data['targetCourse']);
            }
            if (data.hasOwnProperty('copy')) {
                obj['copy'] = CopyV2.constructFromObject(data['copy']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/TargetCourseV2} targetCourse
    */
    'targetCourse' = undefined;
    /**
    * @member {module:model/CopyV2} copy
    */
    'copy' = undefined;




}
