/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body21 model module.
* @module model/Body21
* @version 3900.6.0
*/
export default class Body21 {
    /**
    * Constructs a new <code>Body21</code>.
    * @alias module:model/Body21
    * @class
    * @param uploadId {String} 
    */

    constructor(uploadId) {
        
        
        this['uploadId'] = uploadId;
        
    }

    /**
    * Constructs a <code>Body21</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body21} obj Optional instance to populate.
    * @return {module:model/Body21} The populated <code>Body21</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body21();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('uploadId')) {
                obj['uploadId'] = ApiClient.convertToType(data['uploadId'], 'String');
            }
        }
        return obj;
    }

    /**
    * The name of the file which has been attached to an Attempt including the file extension.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} uploadId
    */
    'uploadId' = undefined;




}
