/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body4 model module.
* @module model/Body4
* @version 3900.6.0
*/
export default class Body4 {
    /**
    * Constructs a new <code>Body4</code>.
    * @alias module:model/Body4
    * @class
    * @param meetingId {String} The primary id of the meeting.
    * @param userId {String} The learn external id of the user.
    * @param status {module:model/Body4.StatusEnum} The attendance status of the user.   | Type      | Description  | --------- | --------- | | Absent |  | | Late |  | | Present |  | | Excused |  | 
    */

    constructor(meetingId, userId, status) {
        
        
        this['meetingId'] = meetingId;
        this['userId'] = userId;
        this['status'] = status;
        
    }

    /**
    * Constructs a <code>Body4</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body4} obj Optional instance to populate.
    * @return {module:model/Body4} The populated <code>Body4</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body4();
                        
            
            if (data.hasOwnProperty('meetingId')) {
                obj['meetingId'] = ApiClient.convertToType(data['meetingId'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * The primary id of the meeting.
    * @member {String} meetingId
    */
    'meetingId' = undefined;
    /**
    * The learn external id of the user.
    * @member {String} userId
    */
    'userId' = undefined;
    /**
    * The attendance status of the user.   | Type      | Description  | --------- | --------- | | Absent |  | | Late |  | | Present |  | | Excused |  | 
    * @member {module:model/Body4.StatusEnum} status
    */
    'status' = undefined;



    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
        /**
         * value: "Absent"
         * @const
         */
        "Absent": "Absent",
        /**
         * value: "Late"
         * @const
         */
        "Late": "Late",
        /**
         * value: "Present"
         * @const
         */
        "Present": "Present",
        /**
         * value: "Excused"
         * @const
         */
        "Excused": "Excused"    };

}
