/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CourseV2 from './CourseV2';

/**
* The CategoryCourseMembership model module.
* @module model/CategoryCourseMembership
* @version 3900.6.0
*/
export default class CategoryCourseMembership {
    /**
    * Constructs a new <code>CategoryCourseMembership</code>.
    * @alias module:model/CategoryCourseMembership
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CategoryCourseMembership</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CategoryCourseMembership} obj Optional instance to populate.
    * @return {module:model/CategoryCourseMembership} The populated <code>CategoryCourseMembership</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryCourseMembership();
                        
            
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'String');
            }
            if (data.hasOwnProperty('categoryType')) {
                obj['categoryType'] = ApiClient.convertToType(data['categoryType'], 'String');
            }
            if (data.hasOwnProperty('courseId')) {
                obj['courseId'] = ApiClient.convertToType(data['courseId'], 'String');
            }
            if (data.hasOwnProperty('course')) {
                obj['course'] = CourseV2.constructFromObject(data['course']);
            }
            if (data.hasOwnProperty('dataSourceId')) {
                obj['dataSourceId'] = ApiClient.convertToType(data['dataSourceId'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The category ID.
    * @member {String} categoryId
    */
    'categoryId' = undefined;
    /**
    * The category type.   | Type      | Description  | --------- | --------- | | Course |  | | Organization |  | 
    * @member {module:model/CategoryCourseMembership.CategoryTypeEnum} categoryType
    */
    'categoryType' = undefined;
    /**
    * The course ID.
    * @member {String} courseId
    */
    'courseId' = undefined;
    /**
    * @member {module:model/CourseV2} course
    */
    'course' = undefined;
    /**
    * The data source ID.
    * @member {String} dataSourceId
    */
    'dataSourceId' = undefined;
    /**
    * The date this membership was created.
    * @member {Date} created
    */
    'created' = undefined;



    /**
    * Allowed values for the <code>categoryType</code> property.
    * @enum {String}
    * @readonly
    */
    static CategoryTypeEnum = {
        /**
         * value: "Course"
         * @const
         */
        "Course": "Course",
        /**
         * value: "Organization"
         * @const
         */
        "Organization": "Organization"    };

}
