/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Course from './Course';

/**
* The CourseChild model module.
* @module model/CourseChild
* @version 3900.6.0
*/
export default class CourseChild {
    /**
    * Constructs a new <code>CourseChild</code>.
    * @alias module:model/CourseChild
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CourseChild</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CourseChild} obj Optional instance to populate.
    * @return {module:model/CourseChild} The populated <code>CourseChild</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CourseChild();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('dataSourceId')) {
                obj['dataSourceId'] = ApiClient.convertToType(data['dataSourceId'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('childCourse')) {
                obj['childCourse'] = Course.constructFromObject(data['childCourse']);
            }
        }
        return obj;
    }

    /**
    * The primary ID of the child course associated with this cross-listing.
    * @member {String} id
    */
    'id' = undefined;
    /**
    * The primary ID of the parent course associated with this cross-listing.
    * @member {String} parentId
    */
    'parentId' = undefined;
    /**
    * The ID of the data source associated with this course cross-listing.  This may optionally be the data source's externalId using the syntax \"externalId:math101\".
    * @member {String} dataSourceId
    */
    'dataSourceId' = undefined;
    /**
    * The date this course cross-listing was created.
    * @member {Date} created
    */
    'created' = undefined;
    /**
    * @member {module:model/Course} childCourse
    */
    'childCourse' = undefined;




}
