/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Availability12 from './Availability12';

/**
* The CourseAnnouncement model module.
* @module model/CourseAnnouncement
* @version 3900.6.0
*/
export default class CourseAnnouncement {
    /**
    * Constructs a new <code>CourseAnnouncement</code>.
    * @alias module:model/CourseAnnouncement
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CourseAnnouncement</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CourseAnnouncement} obj Optional instance to populate.
    * @return {module:model/CourseAnnouncement} The populated <code>CourseAnnouncement</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CourseAnnouncement();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
            if (data.hasOwnProperty('draft')) {
                obj['draft'] = ApiClient.convertToType(data['draft'], 'Boolean');
            }
            if (data.hasOwnProperty('availability')) {
                obj['availability'] = Availability12.constructFromObject(data['availability']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('readCount')) {
                obj['readCount'] = ApiClient.convertToType(data['readCount'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Primary key identifier
    * @member {String} id
    */
    'id' = undefined;
    /**
    * The title of this Announcement.
    * @member {String} title
    */
    'title' = undefined;
    /**
    * The message body of the Announcement. This field supports BbML; see <a target='_blank' href='https://docs.blackboard.com/learn/REST/Blackboard%20Markup%20Language%20-%20BbML.html'>here</a> for more information.
    * @member {String} body
    */
    'body' = undefined;
    /**
    * The user that created the Announcement.
    * @member {String} creator
    */
    'creator' = undefined;
    /**
    * An indication of whether or not the Announcement is in draft status.
    * @member {Boolean} draft
    */
    'draft' = undefined;
    /**
    * @member {module:model/Availability12} availability
    */
    'availability' = undefined;
    /**
    * The date that the Announcement was created.
    * @member {Date} created
    */
    'created' = undefined;
    /**
    * @member {Date} modified
    */
    'modified' = undefined;
    /**
    * The number of users that the Announcement will reach.  Shown when adding the query parameter: \"expand=readCount\".
    * @member {Number} participants
    */
    'participants' = undefined;
    /**
    * The position of the Announcement.
    * @member {Number} position
    */
    'position' = undefined;
    /**
    * The number of reads for the Announcement.  Shown when adding the query parameter: \"expand=readCount\".
    * @member {Number} readCount
    */
    'readCount' = undefined;




}
