/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DataSource model module.
* @module model/DataSource
* @version 3900.6.0
*/
export default class DataSource {
    /**
    * Constructs a new <code>DataSource</code>.
    * @alias module:model/DataSource
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DataSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DataSource} obj Optional instance to populate.
    * @return {module:model/DataSource} The populated <code>DataSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataSource();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * The primary ID of the data source.
    * @member {String} id
    */
    'id' = undefined;
    /**
    * An externally-defined unique ID for the data source.  Formerly known as 'batchUid'.
    * @member {String} externalId
    */
    'externalId' = undefined;
    /**
    * The description of the data source.
    * @member {String} description
    */
    'description' = undefined;




}
