/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DynamicCalendarItemProps model module.
* @module model/DynamicCalendarItemProps
* @version 3900.6.0
*/
export default class DynamicCalendarItemProps {
    /**
    * Constructs a new <code>DynamicCalendarItemProps</code>.
    * Extra calendar item properties if it is a GradebookColumn calendar item.
    * @alias module:model/DynamicCalendarItemProps
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DynamicCalendarItemProps</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DynamicCalendarItemProps} obj Optional instance to populate.
    * @return {module:model/DynamicCalendarItemProps} The populated <code>DynamicCalendarItemProps</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DynamicCalendarItemProps();
                        
            
            if (data.hasOwnProperty('attemptable')) {
                obj['attemptable'] = ApiClient.convertToType(data['attemptable'], 'Boolean');
            }
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'String');
            }
            if (data.hasOwnProperty('dateRangeLimited')) {
                obj['dateRangeLimited'] = ApiClient.convertToType(data['dateRangeLimited'], 'Boolean');
            }
            if (data.hasOwnProperty('eventType')) {
                obj['eventType'] = ApiClient.convertToType(data['eventType'], 'String');
            }
            if (data.hasOwnProperty('gradable')) {
                obj['gradable'] = ApiClient.convertToType(data['gradable'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * The dynamic calendar item can be attempted (can have attempts made against it) and the current user (in context) has permission/entitlement to grade attempts for the object represented by this calendar item.
    * @member {Boolean} attemptable
    */
    'attemptable' = undefined;
    /**
    * Returns the gradeableItem categoryId value .it is only set if the calendar event is dynamically created based on a single grade book column
    * @member {String} categoryId
    */
    'categoryId' = undefined;
    /**
    * The dynamic calendar item is only visible during a specific windows of time.
    * @member {Boolean} dateRangeLimited
    */
    'dateRangeLimited' = undefined;
    /**
    * Returns a human readable string describing the type of calendar item represented (e.g. assignment, test, etc.).
    * @member {String} eventType
    */
    'eventType' = undefined;
    /**
    * The dynamic calendar item can be graded and the current user (in context) has permission/entitlement to grade attempts for the object represented by this calendar item.
    * @member {Boolean} gradable
    */
    'gradable' = undefined;




}
