/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SignupSheet from './SignupSheet';

/**
* The Enrollment4 model module.
* @module model/Enrollment4
* @version 3900.6.0
*/
export default class Enrollment4 {
    /**
    * Constructs a new <code>Enrollment4</code>.
    * Settings controlling enrollment of the group to students.
    * @alias module:model/Enrollment4
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Enrollment4</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Enrollment4} obj Optional instance to populate.
    * @return {module:model/Enrollment4} The populated <code>Enrollment4</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Enrollment4();
                        
            
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('signupSheet')) {
                obj['signupSheet'] = SignupSheet.constructFromObject(data['signupSheet']);
            }
        }
        return obj;
    }

    /**
    * Whether the Group allows self enrollment or only enrolled by instructor. This can only be set on creation.   | Type      | Description  | --------- | --------- | | InstructorOnly | Students are added to the Group by the instructor | | SelfEnrollment | Students are added to the Group by self enrollment | 
    * @member {module:model/Enrollment4.TypeEnum} type
    */
    'type' = undefined;
    /**
    * The maximum allowed enrollment size for self enrolled groups.
    * @member {Number} limit
    */
    'limit' = undefined;
    /**
    * @member {module:model/SignupSheet} signupSheet
    */
    'signupSheet' = undefined;



    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
        /**
         * value: "InstructorOnly"
         * @const
         */
        "InstructorOnly": "InstructorOnly",
        /**
         * value: "SelfEnrollment"
         * @const
         */
        "SelfEnrollment": "SelfEnrollment"    };

}
