/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Availability5 from './Availability5';
import Grading6 from './Grading6';
import GradingFormulaV2 from './GradingFormulaV2';
import Score1 from './Score1';

/**
* The GradeColumnV2 model module.
* @module model/GradeColumnV2
* @version 3900.6.0
*/
export default class GradeColumnV2 {
    /**
    * Constructs a new <code>GradeColumnV2</code>.
    * @alias module:model/GradeColumnV2
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GradeColumnV2</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GradeColumnV2} obj Optional instance to populate.
    * @return {module:model/GradeColumnV2} The populated <code>GradeColumnV2</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GradeColumnV2();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('externalToolId')) {
                obj['externalToolId'] = ApiClient.convertToType(data['externalToolId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('externalGrade')) {
                obj['externalGrade'] = ApiClient.convertToType(data['externalGrade'], 'Boolean');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('contentId')) {
                obj['contentId'] = ApiClient.convertToType(data['contentId'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = Score1.constructFromObject(data['score']);
            }
            if (data.hasOwnProperty('availability')) {
                obj['availability'] = Availability5.constructFromObject(data['availability']);
            }
            if (data.hasOwnProperty('grading')) {
                obj['grading'] = Grading6.constructFromObject(data['grading']);
            }
            if (data.hasOwnProperty('gradebookCategoryId')) {
                obj['gradebookCategoryId'] = ApiClient.convertToType(data['gradebookCategoryId'], 'String');
            }
            if (data.hasOwnProperty('formula')) {
                obj['formula'] = GradingFormulaV2.constructFromObject(data['formula']);
            }
            if (data.hasOwnProperty('includeInCalculations')) {
                obj['includeInCalculations'] = ApiClient.convertToType(data['includeInCalculations'], 'Boolean');
            }
            if (data.hasOwnProperty('showStatisticsToStudents')) {
                obj['showStatisticsToStudents'] = ApiClient.convertToType(data['showStatisticsToStudents'], 'Boolean');
            }
            if (data.hasOwnProperty('scoreProviderHandle')) {
                obj['scoreProviderHandle'] = ApiClient.convertToType(data['scoreProviderHandle'], 'String');
            }
        }
        return obj;
    }

    /**
    * The primary ID of the grade column.
    * @member {String} id
    */
    'id' = undefined;
    /**
    * The externalId for this grade column
    * @member {String} externalId
    */
    'externalId' = undefined;
    /**
    * The externalId for this grade column  **Since**: 3500.2.0
    * @member {String} externalToolId
    */
    'externalToolId' = undefined;
    /**
    * The name of the grade column.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * The display name of the grade column. Only applicable for Classic courses. Ultra courses will simply use the `name` field.  **Since**: 3300.2.0
    * @member {String} displayName
    */
    'displayName' = undefined;
    /**
    * The description of the grade column.
    * @member {String} description
    */
    'description' = undefined;
    /**
    * Whether this grade column is an external grade column.
    * @member {Boolean} externalGrade
    */
    'externalGrade' = undefined;
    /**
    * The date this grade column was created.
    * @member {Date} created
    */
    'created' = undefined;
    /**
    * For grade columns associated with a content item, the ID of the content item.  **Since**: 3000.11.0
    * @member {String} contentId
    */
    'contentId' = undefined;
    /**
    * @member {module:model/Score1} score
    */
    'score' = undefined;
    /**
    * @member {module:model/Availability5} availability
    */
    'availability' = undefined;
    /**
    * @member {module:model/Grading6} grading
    */
    'grading' = undefined;
    /**
    * The gradebook category ID for the grade column.  **Since**: 3400.2.0
    * @member {String} gradebookCategoryId
    */
    'gradebookCategoryId' = undefined;
    /**
    * @member {module:model/GradingFormulaV2} formula
    */
    'formula' = undefined;
    /**
    * Indicates whether or not this column is included in gradebook calculations. Cannot be set for Ultra courses. Default: true  **Since**: 3800.4.0
    * @member {Boolean} includeInCalculations
    */
    'includeInCalculations' = undefined;
    /**
    * Indicates whether or not column statistics are shown to students. Read-only for Ultra courses. Default: false  **Since**: 3800.4.0
    * @member {Boolean} showStatisticsToStudents
    */
    'showStatisticsToStudents' = undefined;
    /**
    * The score provider handle for the grade column.  **Since**: 3900.3.0
    * @member {String} scoreProviderHandle
    */
    'scoreProviderHandle' = undefined;




}
