/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CourseV2 from './CourseV2';

/**
* The HierarchyNodeCourse model module.
* @module model/HierarchyNodeCourse
* @version 3900.6.0
*/
export default class HierarchyNodeCourse {
    /**
    * Constructs a new <code>HierarchyNodeCourse</code>.
    * @alias module:model/HierarchyNodeCourse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HierarchyNodeCourse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HierarchyNodeCourse} obj Optional instance to populate.
    * @return {module:model/HierarchyNodeCourse} The populated <code>HierarchyNodeCourse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HierarchyNodeCourse();
                        
            
            if (data.hasOwnProperty('nodeId')) {
                obj['nodeId'] = ApiClient.convertToType(data['nodeId'], 'String');
            }
            if (data.hasOwnProperty('courseId')) {
                obj['courseId'] = ApiClient.convertToType(data['courseId'], 'String');
            }
            if (data.hasOwnProperty('course')) {
                obj['course'] = CourseV2.constructFromObject(data['course']);
            }
            if (data.hasOwnProperty('isPrimary')) {
                obj['isPrimary'] = ApiClient.convertToType(data['isPrimary'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * The primary ID of the Hierarchy Node
    * @member {String} nodeId
    */
    'nodeId' = undefined;
    /**
    * The primary ID of the Course
    * @member {String} courseId
    */
    'courseId' = undefined;
    /**
    * @member {module:model/CourseV2} course
    */
    'course' = undefined;
    /**
    * Whether or not this association represents the primary node association of the course
    * @member {Boolean} isPrimary
    */
    'isPrimary' = undefined;




}
