/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Job model module.
* @module model/Job
* @version 3900.6.0
*/
export default class Job {
    /**
    * Constructs a new <code>Job</code>.
    * The user&#x27;s job information.
    * @alias module:model/Job
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Job</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Job} obj Optional instance to populate.
    * @return {module:model/Job} The populated <code>Job</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Job();
                        
            
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
        }
        return obj;
    }

    /**
    * The user's job title.
    * @member {String} title
    */
    'title' = undefined;
    /**
    * The department the user belongs to.
    * @member {String} department
    */
    'department' = undefined;
    /**
    * The company the user works for.
    * @member {String} company
    */
    'company' = undefined;




}
