/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Name model module.
* @module model/Name
* @version 3900.6.0
*/
export default class Name {
    /**
    * Constructs a new <code>Name</code>.
    * Properties used to build the user&#x27;s display name.
    * @alias module:model/Name
    * @class
    * @param given {String} The given (first) name of this user.
    * @param family {String} The family (last) name of this user.
    */

    constructor(given, family) {
        
        
        this['given'] = given;
        this['family'] = family;
        
    }

    /**
    * Constructs a <code>Name</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Name} obj Optional instance to populate.
    * @return {module:model/Name} The populated <code>Name</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Name();
                        
            
            if (data.hasOwnProperty('given')) {
                obj['given'] = ApiClient.convertToType(data['given'], 'String');
            }
            if (data.hasOwnProperty('family')) {
                obj['family'] = ApiClient.convertToType(data['family'], 'String');
            }
            if (data.hasOwnProperty('middle')) {
                obj['middle'] = ApiClient.convertToType(data['middle'], 'String');
            }
            if (data.hasOwnProperty('other')) {
                obj['other'] = ApiClient.convertToType(data['other'], 'String');
            }
            if (data.hasOwnProperty('suffix')) {
                obj['suffix'] = ApiClient.convertToType(data['suffix'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
    * The given (first) name of this user.
    * @member {String} given
    */
    'given' = undefined;
    /**
    * The family (last) name of this user.
    * @member {String} family
    */
    'family' = undefined;
    /**
    * The middle name of this user.
    * @member {String} middle
    */
    'middle' = undefined;
    /**
    * The other name (nickname) of this user.
    * @member {String} other
    */
    'other' = undefined;
    /**
    * The suffix of this user's name.  Examples: Jr., III, PhD.
    * @member {String} suffix
    */
    'suffix' = undefined;
    /**
    * The title of this user.  Examples: Mr., Ms., Dr.
    * @member {String} title
    */
    'title' = undefined;




}
