/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ReviewStatus model module.
* @module model/ReviewStatus
* @version 3900.6.0
*/
export default class ReviewStatus {
    /**
    * Constructs a new <code>ReviewStatus</code>.
    * @alias module:model/ReviewStatus
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ReviewStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReviewStatus} obj Optional instance to populate.
    * @return {module:model/ReviewStatus} The populated <code>ReviewStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReviewStatus();
                        
            
            if (data.hasOwnProperty('contentId')) {
                obj['contentId'] = ApiClient.convertToType(data['contentId'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('reviewed')) {
                obj['reviewed'] = ApiClient.convertToType(data['reviewed'], 'Boolean');
            }
            if (data.hasOwnProperty('reviewDate')) {
                obj['reviewDate'] = ApiClient.convertToType(data['reviewDate'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The ID of the content.  **Since**: 3700.16.0
    * @member {String} contentId
    */
    'contentId' = undefined;
    /**
    * The ID of the user.  **Since**: 3700.16.0
    * @member {String} userId
    */
    'userId' = undefined;
    /**
    * The current status of the content's 'reviewed' attribute.  **Since**: 3700.16.0
    * @member {Boolean} reviewed
    */
    'reviewed' = undefined;
    /**
    * The date that the user marked the content as reviewed  **Since**: 3700.16.0
    * @member {Date} reviewDate
    */
    'reviewDate' = undefined;




}
