/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Score1 model module.
* @module model/Score1
* @version 3900.6.0
*/
export default class Score1 {
    /**
    * Constructs a new <code>Score1</code>.
    * Settings controlling the numerical scoring of this grade column.
    * @alias module:model/Score1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Score1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Score1} obj Optional instance to populate.
    * @return {module:model/Score1} The populated <code>Score1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Score1();
                        
            
            if (data.hasOwnProperty('possible')) {
                obj['possible'] = ApiClient.convertToType(data['possible'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The points possible for this grade column.
    * @member {Number} possible
    */
    'possible' = undefined;




}
