/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SignupSheet model module.
* @module model/SignupSheet
* @version 3900.6.0
*/
export default class SignupSheet {
    /**
    * Constructs a new <code>SignupSheet</code>.
    * Settings controlling signup to the group for students. Only applicable if Enrollment.Type allows self enrollment.
    * @alias module:model/SignupSheet
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SignupSheet</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SignupSheet} obj Optional instance to populate.
    * @return {module:model/SignupSheet} The populated <code>SignupSheet</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignupSheet();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('showMembers')) {
                obj['showMembers'] = ApiClient.convertToType(data['showMembers'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * The name of the signup sheet
    * @member {String} name
    */
    'name' = undefined;
    /**
    * The description of the signup sheet This field supports BbML; see <a target='_blank' href='https://docs.blackboard.com/learn/REST/Blackboard%20Markup%20Language%20-%20BbML.html'>here</a> for more information.
    * @member {String} description
    */
    'description' = undefined;
    /**
    * A boolean indicating whether or not members can be seen by others prior to signing up.
    * @member {Boolean} showMembers
    */
    'showMembers' = undefined;




}
