/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Version from './Version';

/**
* The VersionInfo model module.
* @module model/VersionInfo
* @version 3900.6.0
*/
export default class VersionInfo {
    /**
    * Constructs a new <code>VersionInfo</code>.
    * @alias module:model/VersionInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VersionInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VersionInfo} obj Optional instance to populate.
    * @return {module:model/VersionInfo} The populated <code>VersionInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionInfo();
                        
            
            if (data.hasOwnProperty('learn')) {
                obj['learn'] = Version.constructFromObject(data['learn']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Version} learn
    */
    'learn' = undefined;




}
