/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Body22 from '../model/Body22';
import Body23 from '../model/Body23';
import GradeNotation from '../model/GradeNotation';
import InlineResponse20015 from '../model/InlineResponse20015';
import RestException from '../model/RestException';

/**
* CourseGradeNotations service.
* @module api/CourseGradeNotationsApi
* @version 3900.6.0
*/
export default class CourseGradeNotationsApi {

    /**
    * Constructs a new CourseGradeNotationsApi. 
    * @alias module:api/CourseGradeNotationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGet operation.
     * @callback module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20015} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Grade Notations
     * Returns a list of grade notations.  The entitlement \&quot;course.user.grades.VIEW\&quot; is needed.  **Since**: 3200.13.0
     * @param {Object} opts Optional parameters
     * @param {module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20015}
     */
    learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGet(courseId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'courseId': courseId
      };
      let queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit'],
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20015;

      return this.apiClient.callApi(
        '/learn/api/public/v1/courses/{courseId}/gradebook/gradeNotations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdDelete operation.
     * @callback module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Grade Notation
     * Delete a specific grade notation.  The entitlement \&quot;course.gradebook.MODIFY\&quot; is needed.  **Since**: 3200.13.0
     * @param {module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdDelete(courseId, gradeNotationId, callback) {
      let postBody = null;

      let pathParams = {
        'courseId': courseId,
        'gradeNotationId': gradeNotationId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/learn/api/public/v1/courses/{courseId}/gradebook/gradeNotations/{gradeNotationId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdGet operation.
     * @callback module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GradeNotation} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Grade Notation
     * Returns a specific grade notation.  The entitlement \&quot;course.user.grades.VIEW\&quot; is needed.  **Since**: 3200.13.0
     * @param {Object} opts Optional parameters
     * @param {module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GradeNotation}
     */
    learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdGet(courseId, gradeNotationId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'courseId': courseId,
        'gradeNotationId': gradeNotationId
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GradeNotation;

      return this.apiClient.callApi(
        '/learn/api/public/v1/courses/{courseId}/gradebook/gradeNotations/{gradeNotationId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdPatch operation.
     * @callback module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GradeNotation} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Grade Notation
     * Update a grade notation on this course.  The entitlement \&quot;course.gradebook.MODIFY\&quot; is needed.  **Since**: 3200.14.0
     * @param {Object} opts Optional parameters
     * @param {module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GradeNotation}
     */
    learnApiPublicV1CoursesCourseIdGradebookGradeNotationsGradeNotationIdPatch(body, courseId, gradeNotationId, opts, callback) {
      opts = opts || {};
      let postBody = body;

      let pathParams = {
        'courseId': courseId,
        'gradeNotationId': gradeNotationId
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GradeNotation;

      return this.apiClient.callApi(
        '/learn/api/public/v1/courses/{courseId}/gradebook/gradeNotations/{gradeNotationId}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the learnApiPublicV1CoursesCourseIdGradebookGradeNotationsPost operation.
     * @callback module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GradeNotation} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Grade Notation
     * Create a grade notation on this course.  The entitlement \&quot;course.gradebook.MODIFY\&quot; is needed.  **Since**: 3200.13.0
     * @param {Object} opts Optional parameters
     * @param {module:api/CourseGradeNotationsApi~learnApiPublicV1CoursesCourseIdGradebookGradeNotationsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GradeNotation}
     */
    learnApiPublicV1CoursesCourseIdGradebookGradeNotationsPost(body, courseId, opts, callback) {
      opts = opts || {};
      let postBody = body;

      let pathParams = {
        'courseId': courseId
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GradeNotation;

      return this.apiClient.callApi(
        '/learn/api/public/v1/courses/{courseId}/gradebook/gradeNotations', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
