/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import InlineResponse20037 from '../model/InlineResponse20037';
import RestException from '../model/RestException';

/**
* PerformanceDashboard service.
* @module api/PerformanceDashboardApi
* @version 3900.6.0
*/
export default class PerformanceDashboardApi {

    /**
    * Constructs a new PerformanceDashboardApi. 
    * @alias module:api/PerformanceDashboardApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the learnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusGet operation.
     * @callback module:api/PerformanceDashboardApi~learnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20037} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Review Status By Course Id
     * List the content review statuses for all the users enrolled in a course. Users calling this endpoint must have the following entitlement: this entitlement check.  - course.performance.dashboard.VIEW  **Since**: 3700.15.0
     * @param {Object} opts Optional parameters
     * @param {module:api/PerformanceDashboardApi~learnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20037}
     */
    learnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusGet(courseId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'courseId': courseId
      };
      let queryParams = {
        'userId': opts['userId'],
        'offset': opts['offset'],
        'limit': opts['limit'],
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20037;

      return this.apiClient.callApi(
        '/learn/api/public/v1/courses/{courseId}/performance/contentReviewStatus', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
