/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.GradeV2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GradeV2', function() {
    it('should create an instance of GradeV2', function() {
      // uncomment below and update the code to test GradeV2
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be.a(LearnApIs.GradeV2);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property columnId (base name: "columnId")', function() {
      // uncomment below and update the code to test the property columnId
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property displayGrade (base name: "displayGrade")', function() {
      // uncomment below and update the code to test the property displayGrade
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property overridden (base name: "overridden")', function() {
      // uncomment below and update the code to test the property overridden
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property feedback (base name: "feedback")', function() {
      // uncomment below and update the code to test the property feedback
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property exempt (base name: "exempt")', function() {
      // uncomment below and update the code to test the property exempt
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property corrupt (base name: "corrupt")', function() {
      // uncomment below and update the code to test the property corrupt
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property gradeNotationId (base name: "gradeNotationId")', function() {
      // uncomment below and update the code to test the property gradeNotationId
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

    it('should have the property changeIndex (base name: "changeIndex")', function() {
      // uncomment below and update the code to test the property changeIndex
      //var instane = new LearnApIs.GradeV2();
      //expect(instance).to.be();
    });

  });

}));
