/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.LTIDomainConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LTIDomainConfig', function() {
    it('should create an instance of LTIDomainConfig', function() {
      // uncomment below and update the code to test LTIDomainConfig
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be.a(LearnApIs.LTIDomainConfig);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property primaryDomain (base name: "primaryDomain")', function() {
      // uncomment below and update the code to test the property primaryDomain
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "clientId")', function() {
      // uncomment below and update the code to test the property clientId
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property perLinkCredentials (base name: "perLinkCredentials")', function() {
      // uncomment below and update the code to test the property perLinkCredentials
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property sendUserDataType (base name: "sendUserDataType")', function() {
      // uncomment below and update the code to test the property sendUserDataType
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property sendRole (base name: "sendRole")', function() {
      // uncomment below and update the code to test the property sendRole
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property sendName (base name: "sendName")', function() {
      // uncomment below and update the code to test the property sendName
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property sendEmail (base name: "sendEmail")', function() {
      // uncomment below and update the code to test the property sendEmail
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property useSplashScreen (base name: "useSplashScreen")', function() {
      // uncomment below and update the code to test the property useSplashScreen
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property allowMembershipService (base name: "allowMembershipService")', function() {
      // uncomment below and update the code to test the property allowMembershipService
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property allowGradesService (base name: "allowGradesService")', function() {
      // uncomment below and update the code to test the property allowGradesService
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property publicKey (base name: "publicKey")', function() {
      // uncomment below and update the code to test the property publicKey
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property jwksUrl (base name: "jwksUrl")', function() {
      // uncomment below and update the code to test the property jwksUrl
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property allowEdit (base name: "allowEdit")', function() {
      // uncomment below and update the code to test the property allowEdit
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

    it('should have the property customParameters (base name: "customParameters")', function() {
      // uncomment below and update the code to test the property customParameters
      //var instane = new LearnApIs.LTIDomainConfig();
      //expect(instance).to.be();
    });

  });

}));
