/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.Question();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Question', function() {
    it('should create an instance of Question', function() {
      // uncomment below and update the code to test Question
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be.a(LearnApIs.Question);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property points (base name: "points")', function() {
      // uncomment below and update the code to test the property points
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property correctResponseFeedback (base name: "correctResponseFeedback")', function() {
      // uncomment below and update the code to test the property correctResponseFeedback
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property incorrectResponseFeedback (base name: "incorrectResponseFeedback")', function() {
      // uncomment below and update the code to test the property incorrectResponseFeedback
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property instructorNotes (base name: "instructorNotes")', function() {
      // uncomment below and update the code to test the property instructorNotes
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

    it('should have the property questionHandler (base name: "questionHandler")', function() {
      // uncomment below and update the code to test the property questionHandler
      //var instane = new LearnApIs.Question();
      //expect(instance).to.be();
    });

  });

}));
