/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AdaptiveRelease from './model/AdaptiveRelease';
import AdaptiveRelease1 from './model/AdaptiveRelease1';
import Address from './model/Address';
import AggregateReviewStatus from './model/AggregateReviewStatus';
import Announcement from './model/Announcement';
import AnonymousGrading from './model/AnonymousGrading';
import AnonymousGrading1 from './model/AnonymousGrading1';
import Attempt from './model/Attempt';
import AttemptFile from './model/AttemptFile';
import AttemptV2 from './model/AttemptV2';
import AttendanceDataDownloadUrl from './model/AttendanceDataDownloadUrl';
import AttendanceRecord from './model/AttendanceRecord';
import Availability from './model/Availability';
import Availability1 from './model/Availability1';
import Availability10 from './model/Availability10';
import Availability11 from './model/Availability11';
import Availability12 from './model/Availability12';
import Availability13 from './model/Availability13';
import Availability14 from './model/Availability14';
import Availability2 from './model/Availability2';
import Availability3 from './model/Availability3';
import Availability4 from './model/Availability4';
import Availability5 from './model/Availability5';
import Availability6 from './model/Availability6';
import Availability7 from './model/Availability7';
import Availability8 from './model/Availability8';
import Availability9 from './model/Availability9';
import Avatar from './model/Avatar';
import Avatar1 from './model/Avatar1';
import BYDAYEnum from './model/BYDAYEnum';
import Body from './model/Body';
import Body1 from './model/Body1';
import Body10 from './model/Body10';
import Body11 from './model/Body11';
import Body12 from './model/Body12';
import Body13 from './model/Body13';
import Body14 from './model/Body14';
import Body15 from './model/Body15';
import Body16 from './model/Body16';
import Body17 from './model/Body17';
import Body18 from './model/Body18';
import Body19 from './model/Body19';
import Body2 from './model/Body2';
import Body20 from './model/Body20';
import Body21 from './model/Body21';
import Body22 from './model/Body22';
import Body23 from './model/Body23';
import Body24 from './model/Body24';
import Body25 from './model/Body25';
import Body26 from './model/Body26';
import Body27 from './model/Body27';
import Body28 from './model/Body28';
import Body29 from './model/Body29';
import Body3 from './model/Body3';
import Body30 from './model/Body30';
import Body31 from './model/Body31';
import Body32 from './model/Body32';
import Body33 from './model/Body33';
import Body34 from './model/Body34';
import Body35 from './model/Body35';
import Body36 from './model/Body36';
import Body37 from './model/Body37';
import Body38 from './model/Body38';
import Body39 from './model/Body39';
import Body4 from './model/Body4';
import Body40 from './model/Body40';
import Body41 from './model/Body41';
import Body42 from './model/Body42';
import Body43 from './model/Body43';
import Body44 from './model/Body44';
import Body45 from './model/Body45';
import Body46 from './model/Body46';
import Body47 from './model/Body47';
import Body48 from './model/Body48';
import Body49 from './model/Body49';
import Body5 from './model/Body5';
import Body50 from './model/Body50';
import Body51 from './model/Body51';
import Body52 from './model/Body52';
import Body53 from './model/Body53';
import Body54 from './model/Body54';
import Body55 from './model/Body55';
import Body56 from './model/Body56';
import Body57 from './model/Body57';
import Body58 from './model/Body58';
import Body59 from './model/Body59';
import Body6 from './model/Body6';
import Body60 from './model/Body60';
import Body61 from './model/Body61';
import Body62 from './model/Body62';
import Body63 from './model/Body63';
import Body64 from './model/Body64';
import Body65 from './model/Body65';
import Body66 from './model/Body66';
import Body67 from './model/Body67';
import Body68 from './model/Body68';
import Body69 from './model/Body69';
import Body7 from './model/Body7';
import Body8 from './model/Body8';
import Body9 from './model/Body9';
import Calendar from './model/Calendar';
import CalendarItem from './model/CalendarItem';
import CalendarItemRecurrence from './model/CalendarItemRecurrence';
import Category from './model/Category';
import CategoryCourseMembership from './model/CategoryCourseMembership';
import Contact from './model/Contact';
import Content from './model/Content';
import ContentGroup from './model/ContentGroup';
import ContentHandler from './model/ContentHandler';
import CopyV2 from './model/CopyV2';
import Course from './model/Course';
import CourseAnnouncement from './model/CourseAnnouncement';
import CourseCategoryMembership from './model/CourseCategoryMembership';
import CourseChild from './model/CourseChild';
import CourseHierarchyNode from './model/CourseHierarchyNode';
import CourseIdParam from './model/CourseIdParam';
import CourseMeeting from './model/CourseMeeting';
import CourseMembership from './model/CourseMembership';
import CourseMessage from './model/CourseMessage';
import CourseMessageAttachment from './model/CourseMessageAttachment';
import CourseMessageFolder from './model/CourseMessageFolder';
import CourseMessageParticipant from './model/CourseMessageParticipant';
import CourseMessagesCounts from './model/CourseMessagesCounts';
import CourseRole from './model/CourseRole';
import CourseTask from './model/CourseTask';
import CourseV2 from './model/CourseV2';
import CreateAssignmentResult from './model/CreateAssignmentResult';
import DataSource from './model/DataSource';
import DisplayGrade from './model/DisplayGrade';
import Duration from './model/Duration';
import Duration1 from './model/Duration1';
import Duration2 from './model/Duration2';
import Duration3 from './model/Duration3';
import Duration4 from './model/Duration4';
import Duration5 from './model/Duration5';
import DynamicCalendarItemProps from './model/DynamicCalendarItemProps';
import Enrollment from './model/Enrollment';
import Enrollment1 from './model/Enrollment1';
import Enrollment2 from './model/Enrollment2';
import Enrollment3 from './model/Enrollment3';
import Enrollment4 from './model/Enrollment4';
import FileAttachment from './model/FileAttachment';
import Grade from './model/Grade';
import GradeColumn from './model/GradeColumn';
import GradeColumnV2 from './model/GradeColumnV2';
import GradeNotation from './model/GradeNotation';
import GradeSchema from './model/GradeSchema';
import GradeSymbol from './model/GradeSymbol';
import GradeV2 from './model/GradeV2';
import GradebookCategory from './model/GradebookCategory';
import Grading from './model/Grading';
import Grading1 from './model/Grading1';
import Grading2 from './model/Grading2';
import Grading3 from './model/Grading3';
import Grading4 from './model/Grading4';
import Grading5 from './model/Grading5';
import Grading6 from './model/Grading6';
import GradingFormulaV2 from './model/GradingFormulaV2';
import GradingPeriod from './model/GradingPeriod';
import Group from './model/Group';
import GroupMembership from './model/GroupMembership';
import GroupV2 from './model/GroupV2';
import HierarchyNodeCourse from './model/HierarchyNodeCourse';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse20011 from './model/InlineResponse20011';
import InlineResponse20012 from './model/InlineResponse20012';
import InlineResponse20013 from './model/InlineResponse20013';
import InlineResponse20014 from './model/InlineResponse20014';
import InlineResponse20015 from './model/InlineResponse20015';
import InlineResponse20016 from './model/InlineResponse20016';
import InlineResponse20017 from './model/InlineResponse20017';
import InlineResponse20018 from './model/InlineResponse20018';
import InlineResponse20019 from './model/InlineResponse20019';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse20020 from './model/InlineResponse20020';
import InlineResponse20021 from './model/InlineResponse20021';
import InlineResponse20022 from './model/InlineResponse20022';
import InlineResponse20023 from './model/InlineResponse20023';
import InlineResponse20024 from './model/InlineResponse20024';
import InlineResponse20025 from './model/InlineResponse20025';
import InlineResponse20026 from './model/InlineResponse20026';
import InlineResponse20027 from './model/InlineResponse20027';
import InlineResponse20028 from './model/InlineResponse20028';
import InlineResponse20029 from './model/InlineResponse20029';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse20030 from './model/InlineResponse20030';
import InlineResponse20031 from './model/InlineResponse20031';
import InlineResponse20032 from './model/InlineResponse20032';
import InlineResponse20033 from './model/InlineResponse20033';
import InlineResponse20034 from './model/InlineResponse20034';
import InlineResponse20035 from './model/InlineResponse20035';
import InlineResponse20036 from './model/InlineResponse20036';
import InlineResponse20037 from './model/InlineResponse20037';
import InlineResponse20038 from './model/InlineResponse20038';
import InlineResponse20039 from './model/InlineResponse20039';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse20040 from './model/InlineResponse20040';
import InlineResponse20041 from './model/InlineResponse20041';
import InlineResponse20042 from './model/InlineResponse20042';
import InlineResponse20043 from './model/InlineResponse20043';
import InlineResponse20044 from './model/InlineResponse20044';
import InlineResponse20045 from './model/InlineResponse20045';
import InlineResponse20046 from './model/InlineResponse20046';
import InlineResponse20047 from './model/InlineResponse20047';
import InlineResponse20048 from './model/InlineResponse20048';
import InlineResponse20049 from './model/InlineResponse20049';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse20050 from './model/InlineResponse20050';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InstitutionRole from './model/InstitutionRole';
import Job from './model/Job';
import LTIDomainConfig from './model/LTIDomainConfig';
import LTIPlacement from './model/LTIPlacement';
import Link from './model/Link';
import Locale from './model/Locale';
import Locale1 from './model/Locale1';
import Locale2 from './model/Locale2';
import Name from './model/Name';
import Name1 from './model/Name1';
import Node from './model/Node';
import OAuth2AccessToken from './model/OAuth2AccessToken';
import OAuth2AccessTokenInfo from './model/OAuth2AccessTokenInfo';
import OAuth2Error from './model/OAuth2Error';
import OriginalityReportingTool from './model/OriginalityReportingTool';
import PagingInfo from './model/PagingInfo';
import PrivacyPolicy from './model/PrivacyPolicy';
import ProctoringService from './model/ProctoringService';
import Question from './model/Question';
import QuestionHandler from './model/QuestionHandler';
import Resource from './model/Resource';
import RestException from './model/RestException';
import ReviewStatus from './model/ReviewStatus';
import SISLogEntry from './model/SISLogEntry';
import Score from './model/Score';
import Score1 from './model/Score1';
import Score2 from './model/Score2';
import Session from './model/Session';
import SettingsCopyOptionsV2 from './model/SettingsCopyOptionsV2';
import SignupSheet from './model/SignupSheet';
import SystemRole from './model/SystemRole';
import SystemRoleEnum from './model/SystemRoleEnum';
import SystemTask from './model/SystemTask';
import SystemTaskResult from './model/SystemTaskResult';
import TargetCourseV2 from './model/TargetCourseV2';
import Term from './model/Term';
import UploadedFileInfo from './model/UploadedFileInfo';
import User from './model/User';
import UserMembership from './model/UserMembership';
import Version from './model/Version';
import VersionInfo from './model/VersionInfo';
import AnnouncementsApi from './api/AnnouncementsApi';
import AttendanceApi from './api/AttendanceApi';
import CalendarApi from './api/CalendarApi';
import ContentApi from './api/ContentApi';
import ContentFileAttachmentsApi from './api/ContentFileAttachmentsApi';
import ContentGroupAssignmentsApi from './api/ContentGroupAssignmentsApi';
import ContentResourcesApi from './api/ContentResourcesApi';
import ContentReviewApi from './api/ContentReviewApi';
import CourseAnnouncementsApi from './api/CourseAnnouncementsApi';
import CourseAssessmentsApi from './api/CourseAssessmentsApi';
import CourseCategoriesApi from './api/CourseCategoriesApi';
import CourseGradeAttemptsApi from './api/CourseGradeAttemptsApi';
import CourseGradeNotationsApi from './api/CourseGradeNotationsApi';
import CourseGradebookCategoriesApi from './api/CourseGradebookCategoriesApi';
import CourseGradesApi from './api/CourseGradesApi';
import CourseGradingPeriodsApi from './api/CourseGradingPeriodsApi';
import CourseGroupUsersApi from './api/CourseGroupUsersApi';
import CourseGroupsApi from './api/CourseGroupsApi';
import CourseMembershipsApi from './api/CourseMembershipsApi';
import CourseMessagesApi from './api/CourseMessagesApi';
import CoursesApi from './api/CoursesApi';
import DataSourcesApi from './api/DataSourcesApi';
import DeprecatedCourseGradesApi from './api/DeprecatedCourseGradesApi';
import DeprecatedCourseGroupUsersApi from './api/DeprecatedCourseGroupUsersApi';
import DeprecatedCourseGroupsApi from './api/DeprecatedCourseGroupsApi';
import DeprecatedCoursesApi from './api/DeprecatedCoursesApi';
import InstitutionalHierarchyApi from './api/InstitutionalHierarchyApi';
import LtiApi from './api/LtiApi';
import OauthApi from './api/OauthApi';
import PerformanceDashboardApi from './api/PerformanceDashboardApi';
import ProctoringApi from './api/ProctoringApi';
import RolesApi from './api/RolesApi';
import SISLogsApi from './api/SISLogsApi';
import SessionsApi from './api/SessionsApi';
import SystemApi from './api/SystemApi';
import TermsApi from './api/TermsApi';
import UploadsApi from './api/UploadsApi';
import UsersApi from './api/UsersApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LearnApIs = require('index'); // See note below*.
* var xxxSvc = new LearnApIs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LearnApIs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LearnApIs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LearnApIs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3900.6.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AdaptiveRelease model constructor.
     * @property {module:model/AdaptiveRelease}
     */
    AdaptiveRelease,

    /**
     * The AdaptiveRelease1 model constructor.
     * @property {module:model/AdaptiveRelease1}
     */
    AdaptiveRelease1,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The AggregateReviewStatus model constructor.
     * @property {module:model/AggregateReviewStatus}
     */
    AggregateReviewStatus,

    /**
     * The Announcement model constructor.
     * @property {module:model/Announcement}
     */
    Announcement,

    /**
     * The AnonymousGrading model constructor.
     * @property {module:model/AnonymousGrading}
     */
    AnonymousGrading,

    /**
     * The AnonymousGrading1 model constructor.
     * @property {module:model/AnonymousGrading1}
     */
    AnonymousGrading1,

    /**
     * The Attempt model constructor.
     * @property {module:model/Attempt}
     */
    Attempt,

    /**
     * The AttemptFile model constructor.
     * @property {module:model/AttemptFile}
     */
    AttemptFile,

    /**
     * The AttemptV2 model constructor.
     * @property {module:model/AttemptV2}
     */
    AttemptV2,

    /**
     * The AttendanceDataDownloadUrl model constructor.
     * @property {module:model/AttendanceDataDownloadUrl}
     */
    AttendanceDataDownloadUrl,

    /**
     * The AttendanceRecord model constructor.
     * @property {module:model/AttendanceRecord}
     */
    AttendanceRecord,

    /**
     * The Availability model constructor.
     * @property {module:model/Availability}
     */
    Availability,

    /**
     * The Availability1 model constructor.
     * @property {module:model/Availability1}
     */
    Availability1,

    /**
     * The Availability10 model constructor.
     * @property {module:model/Availability10}
     */
    Availability10,

    /**
     * The Availability11 model constructor.
     * @property {module:model/Availability11}
     */
    Availability11,

    /**
     * The Availability12 model constructor.
     * @property {module:model/Availability12}
     */
    Availability12,

    /**
     * The Availability13 model constructor.
     * @property {module:model/Availability13}
     */
    Availability13,

    /**
     * The Availability14 model constructor.
     * @property {module:model/Availability14}
     */
    Availability14,

    /**
     * The Availability2 model constructor.
     * @property {module:model/Availability2}
     */
    Availability2,

    /**
     * The Availability3 model constructor.
     * @property {module:model/Availability3}
     */
    Availability3,

    /**
     * The Availability4 model constructor.
     * @property {module:model/Availability4}
     */
    Availability4,

    /**
     * The Availability5 model constructor.
     * @property {module:model/Availability5}
     */
    Availability5,

    /**
     * The Availability6 model constructor.
     * @property {module:model/Availability6}
     */
    Availability6,

    /**
     * The Availability7 model constructor.
     * @property {module:model/Availability7}
     */
    Availability7,

    /**
     * The Availability8 model constructor.
     * @property {module:model/Availability8}
     */
    Availability8,

    /**
     * The Availability9 model constructor.
     * @property {module:model/Availability9}
     */
    Availability9,

    /**
     * The Avatar model constructor.
     * @property {module:model/Avatar}
     */
    Avatar,

    /**
     * The Avatar1 model constructor.
     * @property {module:model/Avatar1}
     */
    Avatar1,

    /**
     * The BYDAYEnum model constructor.
     * @property {module:model/BYDAYEnum}
     */
    BYDAYEnum,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The Body1 model constructor.
     * @property {module:model/Body1}
     */
    Body1,

    /**
     * The Body10 model constructor.
     * @property {module:model/Body10}
     */
    Body10,

    /**
     * The Body11 model constructor.
     * @property {module:model/Body11}
     */
    Body11,

    /**
     * The Body12 model constructor.
     * @property {module:model/Body12}
     */
    Body12,

    /**
     * The Body13 model constructor.
     * @property {module:model/Body13}
     */
    Body13,

    /**
     * The Body14 model constructor.
     * @property {module:model/Body14}
     */
    Body14,

    /**
     * The Body15 model constructor.
     * @property {module:model/Body15}
     */
    Body15,

    /**
     * The Body16 model constructor.
     * @property {module:model/Body16}
     */
    Body16,

    /**
     * The Body17 model constructor.
     * @property {module:model/Body17}
     */
    Body17,

    /**
     * The Body18 model constructor.
     * @property {module:model/Body18}
     */
    Body18,

    /**
     * The Body19 model constructor.
     * @property {module:model/Body19}
     */
    Body19,

    /**
     * The Body2 model constructor.
     * @property {module:model/Body2}
     */
    Body2,

    /**
     * The Body20 model constructor.
     * @property {module:model/Body20}
     */
    Body20,

    /**
     * The Body21 model constructor.
     * @property {module:model/Body21}
     */
    Body21,

    /**
     * The Body22 model constructor.
     * @property {module:model/Body22}
     */
    Body22,

    /**
     * The Body23 model constructor.
     * @property {module:model/Body23}
     */
    Body23,

    /**
     * The Body24 model constructor.
     * @property {module:model/Body24}
     */
    Body24,

    /**
     * The Body25 model constructor.
     * @property {module:model/Body25}
     */
    Body25,

    /**
     * The Body26 model constructor.
     * @property {module:model/Body26}
     */
    Body26,

    /**
     * The Body27 model constructor.
     * @property {module:model/Body27}
     */
    Body27,

    /**
     * The Body28 model constructor.
     * @property {module:model/Body28}
     */
    Body28,

    /**
     * The Body29 model constructor.
     * @property {module:model/Body29}
     */
    Body29,

    /**
     * The Body3 model constructor.
     * @property {module:model/Body3}
     */
    Body3,

    /**
     * The Body30 model constructor.
     * @property {module:model/Body30}
     */
    Body30,

    /**
     * The Body31 model constructor.
     * @property {module:model/Body31}
     */
    Body31,

    /**
     * The Body32 model constructor.
     * @property {module:model/Body32}
     */
    Body32,

    /**
     * The Body33 model constructor.
     * @property {module:model/Body33}
     */
    Body33,

    /**
     * The Body34 model constructor.
     * @property {module:model/Body34}
     */
    Body34,

    /**
     * The Body35 model constructor.
     * @property {module:model/Body35}
     */
    Body35,

    /**
     * The Body36 model constructor.
     * @property {module:model/Body36}
     */
    Body36,

    /**
     * The Body37 model constructor.
     * @property {module:model/Body37}
     */
    Body37,

    /**
     * The Body38 model constructor.
     * @property {module:model/Body38}
     */
    Body38,

    /**
     * The Body39 model constructor.
     * @property {module:model/Body39}
     */
    Body39,

    /**
     * The Body4 model constructor.
     * @property {module:model/Body4}
     */
    Body4,

    /**
     * The Body40 model constructor.
     * @property {module:model/Body40}
     */
    Body40,

    /**
     * The Body41 model constructor.
     * @property {module:model/Body41}
     */
    Body41,

    /**
     * The Body42 model constructor.
     * @property {module:model/Body42}
     */
    Body42,

    /**
     * The Body43 model constructor.
     * @property {module:model/Body43}
     */
    Body43,

    /**
     * The Body44 model constructor.
     * @property {module:model/Body44}
     */
    Body44,

    /**
     * The Body45 model constructor.
     * @property {module:model/Body45}
     */
    Body45,

    /**
     * The Body46 model constructor.
     * @property {module:model/Body46}
     */
    Body46,

    /**
     * The Body47 model constructor.
     * @property {module:model/Body47}
     */
    Body47,

    /**
     * The Body48 model constructor.
     * @property {module:model/Body48}
     */
    Body48,

    /**
     * The Body49 model constructor.
     * @property {module:model/Body49}
     */
    Body49,

    /**
     * The Body5 model constructor.
     * @property {module:model/Body5}
     */
    Body5,

    /**
     * The Body50 model constructor.
     * @property {module:model/Body50}
     */
    Body50,

    /**
     * The Body51 model constructor.
     * @property {module:model/Body51}
     */
    Body51,

    /**
     * The Body52 model constructor.
     * @property {module:model/Body52}
     */
    Body52,

    /**
     * The Body53 model constructor.
     * @property {module:model/Body53}
     */
    Body53,

    /**
     * The Body54 model constructor.
     * @property {module:model/Body54}
     */
    Body54,

    /**
     * The Body55 model constructor.
     * @property {module:model/Body55}
     */
    Body55,

    /**
     * The Body56 model constructor.
     * @property {module:model/Body56}
     */
    Body56,

    /**
     * The Body57 model constructor.
     * @property {module:model/Body57}
     */
    Body57,

    /**
     * The Body58 model constructor.
     * @property {module:model/Body58}
     */
    Body58,

    /**
     * The Body59 model constructor.
     * @property {module:model/Body59}
     */
    Body59,

    /**
     * The Body6 model constructor.
     * @property {module:model/Body6}
     */
    Body6,

    /**
     * The Body60 model constructor.
     * @property {module:model/Body60}
     */
    Body60,

    /**
     * The Body61 model constructor.
     * @property {module:model/Body61}
     */
    Body61,

    /**
     * The Body62 model constructor.
     * @property {module:model/Body62}
     */
    Body62,

    /**
     * The Body63 model constructor.
     * @property {module:model/Body63}
     */
    Body63,

    /**
     * The Body64 model constructor.
     * @property {module:model/Body64}
     */
    Body64,

    /**
     * The Body65 model constructor.
     * @property {module:model/Body65}
     */
    Body65,

    /**
     * The Body66 model constructor.
     * @property {module:model/Body66}
     */
    Body66,

    /**
     * The Body67 model constructor.
     * @property {module:model/Body67}
     */
    Body67,

    /**
     * The Body68 model constructor.
     * @property {module:model/Body68}
     */
    Body68,

    /**
     * The Body69 model constructor.
     * @property {module:model/Body69}
     */
    Body69,

    /**
     * The Body7 model constructor.
     * @property {module:model/Body7}
     */
    Body7,

    /**
     * The Body8 model constructor.
     * @property {module:model/Body8}
     */
    Body8,

    /**
     * The Body9 model constructor.
     * @property {module:model/Body9}
     */
    Body9,

    /**
     * The Calendar model constructor.
     * @property {module:model/Calendar}
     */
    Calendar,

    /**
     * The CalendarItem model constructor.
     * @property {module:model/CalendarItem}
     */
    CalendarItem,

    /**
     * The CalendarItemRecurrence model constructor.
     * @property {module:model/CalendarItemRecurrence}
     */
    CalendarItemRecurrence,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The CategoryCourseMembership model constructor.
     * @property {module:model/CategoryCourseMembership}
     */
    CategoryCourseMembership,

    /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
    Contact,

    /**
     * The Content model constructor.
     * @property {module:model/Content}
     */
    Content,

    /**
     * The ContentGroup model constructor.
     * @property {module:model/ContentGroup}
     */
    ContentGroup,

    /**
     * The ContentHandler model constructor.
     * @property {module:model/ContentHandler}
     */
    ContentHandler,

    /**
     * The CopyV2 model constructor.
     * @property {module:model/CopyV2}
     */
    CopyV2,

    /**
     * The Course model constructor.
     * @property {module:model/Course}
     */
    Course,

    /**
     * The CourseAnnouncement model constructor.
     * @property {module:model/CourseAnnouncement}
     */
    CourseAnnouncement,

    /**
     * The CourseCategoryMembership model constructor.
     * @property {module:model/CourseCategoryMembership}
     */
    CourseCategoryMembership,

    /**
     * The CourseChild model constructor.
     * @property {module:model/CourseChild}
     */
    CourseChild,

    /**
     * The CourseHierarchyNode model constructor.
     * @property {module:model/CourseHierarchyNode}
     */
    CourseHierarchyNode,

    /**
     * The CourseIdParam model constructor.
     * @property {module:model/CourseIdParam}
     */
    CourseIdParam,

    /**
     * The CourseMeeting model constructor.
     * @property {module:model/CourseMeeting}
     */
    CourseMeeting,

    /**
     * The CourseMembership model constructor.
     * @property {module:model/CourseMembership}
     */
    CourseMembership,

    /**
     * The CourseMessage model constructor.
     * @property {module:model/CourseMessage}
     */
    CourseMessage,

    /**
     * The CourseMessageAttachment model constructor.
     * @property {module:model/CourseMessageAttachment}
     */
    CourseMessageAttachment,

    /**
     * The CourseMessageFolder model constructor.
     * @property {module:model/CourseMessageFolder}
     */
    CourseMessageFolder,

    /**
     * The CourseMessageParticipant model constructor.
     * @property {module:model/CourseMessageParticipant}
     */
    CourseMessageParticipant,

    /**
     * The CourseMessagesCounts model constructor.
     * @property {module:model/CourseMessagesCounts}
     */
    CourseMessagesCounts,

    /**
     * The CourseRole model constructor.
     * @property {module:model/CourseRole}
     */
    CourseRole,

    /**
     * The CourseTask model constructor.
     * @property {module:model/CourseTask}
     */
    CourseTask,

    /**
     * The CourseV2 model constructor.
     * @property {module:model/CourseV2}
     */
    CourseV2,

    /**
     * The CreateAssignmentResult model constructor.
     * @property {module:model/CreateAssignmentResult}
     */
    CreateAssignmentResult,

    /**
     * The DataSource model constructor.
     * @property {module:model/DataSource}
     */
    DataSource,

    /**
     * The DisplayGrade model constructor.
     * @property {module:model/DisplayGrade}
     */
    DisplayGrade,

    /**
     * The Duration model constructor.
     * @property {module:model/Duration}
     */
    Duration,

    /**
     * The Duration1 model constructor.
     * @property {module:model/Duration1}
     */
    Duration1,

    /**
     * The Duration2 model constructor.
     * @property {module:model/Duration2}
     */
    Duration2,

    /**
     * The Duration3 model constructor.
     * @property {module:model/Duration3}
     */
    Duration3,

    /**
     * The Duration4 model constructor.
     * @property {module:model/Duration4}
     */
    Duration4,

    /**
     * The Duration5 model constructor.
     * @property {module:model/Duration5}
     */
    Duration5,

    /**
     * The DynamicCalendarItemProps model constructor.
     * @property {module:model/DynamicCalendarItemProps}
     */
    DynamicCalendarItemProps,

    /**
     * The Enrollment model constructor.
     * @property {module:model/Enrollment}
     */
    Enrollment,

    /**
     * The Enrollment1 model constructor.
     * @property {module:model/Enrollment1}
     */
    Enrollment1,

    /**
     * The Enrollment2 model constructor.
     * @property {module:model/Enrollment2}
     */
    Enrollment2,

    /**
     * The Enrollment3 model constructor.
     * @property {module:model/Enrollment3}
     */
    Enrollment3,

    /**
     * The Enrollment4 model constructor.
     * @property {module:model/Enrollment4}
     */
    Enrollment4,

    /**
     * The FileAttachment model constructor.
     * @property {module:model/FileAttachment}
     */
    FileAttachment,

    /**
     * The Grade model constructor.
     * @property {module:model/Grade}
     */
    Grade,

    /**
     * The GradeColumn model constructor.
     * @property {module:model/GradeColumn}
     */
    GradeColumn,

    /**
     * The GradeColumnV2 model constructor.
     * @property {module:model/GradeColumnV2}
     */
    GradeColumnV2,

    /**
     * The GradeNotation model constructor.
     * @property {module:model/GradeNotation}
     */
    GradeNotation,

    /**
     * The GradeSchema model constructor.
     * @property {module:model/GradeSchema}
     */
    GradeSchema,

    /**
     * The GradeSymbol model constructor.
     * @property {module:model/GradeSymbol}
     */
    GradeSymbol,

    /**
     * The GradeV2 model constructor.
     * @property {module:model/GradeV2}
     */
    GradeV2,

    /**
     * The GradebookCategory model constructor.
     * @property {module:model/GradebookCategory}
     */
    GradebookCategory,

    /**
     * The Grading model constructor.
     * @property {module:model/Grading}
     */
    Grading,

    /**
     * The Grading1 model constructor.
     * @property {module:model/Grading1}
     */
    Grading1,

    /**
     * The Grading2 model constructor.
     * @property {module:model/Grading2}
     */
    Grading2,

    /**
     * The Grading3 model constructor.
     * @property {module:model/Grading3}
     */
    Grading3,

    /**
     * The Grading4 model constructor.
     * @property {module:model/Grading4}
     */
    Grading4,

    /**
     * The Grading5 model constructor.
     * @property {module:model/Grading5}
     */
    Grading5,

    /**
     * The Grading6 model constructor.
     * @property {module:model/Grading6}
     */
    Grading6,

    /**
     * The GradingFormulaV2 model constructor.
     * @property {module:model/GradingFormulaV2}
     */
    GradingFormulaV2,

    /**
     * The GradingPeriod model constructor.
     * @property {module:model/GradingPeriod}
     */
    GradingPeriod,

    /**
     * The Group model constructor.
     * @property {module:model/Group}
     */
    Group,

    /**
     * The GroupMembership model constructor.
     * @property {module:model/GroupMembership}
     */
    GroupMembership,

    /**
     * The GroupV2 model constructor.
     * @property {module:model/GroupV2}
     */
    GroupV2,

    /**
     * The HierarchyNodeCourse model constructor.
     * @property {module:model/HierarchyNodeCourse}
     */
    HierarchyNodeCourse,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016,

    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017,

    /**
     * The InlineResponse20018 model constructor.
     * @property {module:model/InlineResponse20018}
     */
    InlineResponse20018,

    /**
     * The InlineResponse20019 model constructor.
     * @property {module:model/InlineResponse20019}
     */
    InlineResponse20019,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse20020 model constructor.
     * @property {module:model/InlineResponse20020}
     */
    InlineResponse20020,

    /**
     * The InlineResponse20021 model constructor.
     * @property {module:model/InlineResponse20021}
     */
    InlineResponse20021,

    /**
     * The InlineResponse20022 model constructor.
     * @property {module:model/InlineResponse20022}
     */
    InlineResponse20022,

    /**
     * The InlineResponse20023 model constructor.
     * @property {module:model/InlineResponse20023}
     */
    InlineResponse20023,

    /**
     * The InlineResponse20024 model constructor.
     * @property {module:model/InlineResponse20024}
     */
    InlineResponse20024,

    /**
     * The InlineResponse20025 model constructor.
     * @property {module:model/InlineResponse20025}
     */
    InlineResponse20025,

    /**
     * The InlineResponse20026 model constructor.
     * @property {module:model/InlineResponse20026}
     */
    InlineResponse20026,

    /**
     * The InlineResponse20027 model constructor.
     * @property {module:model/InlineResponse20027}
     */
    InlineResponse20027,

    /**
     * The InlineResponse20028 model constructor.
     * @property {module:model/InlineResponse20028}
     */
    InlineResponse20028,

    /**
     * The InlineResponse20029 model constructor.
     * @property {module:model/InlineResponse20029}
     */
    InlineResponse20029,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse20030 model constructor.
     * @property {module:model/InlineResponse20030}
     */
    InlineResponse20030,

    /**
     * The InlineResponse20031 model constructor.
     * @property {module:model/InlineResponse20031}
     */
    InlineResponse20031,

    /**
     * The InlineResponse20032 model constructor.
     * @property {module:model/InlineResponse20032}
     */
    InlineResponse20032,

    /**
     * The InlineResponse20033 model constructor.
     * @property {module:model/InlineResponse20033}
     */
    InlineResponse20033,

    /**
     * The InlineResponse20034 model constructor.
     * @property {module:model/InlineResponse20034}
     */
    InlineResponse20034,

    /**
     * The InlineResponse20035 model constructor.
     * @property {module:model/InlineResponse20035}
     */
    InlineResponse20035,

    /**
     * The InlineResponse20036 model constructor.
     * @property {module:model/InlineResponse20036}
     */
    InlineResponse20036,

    /**
     * The InlineResponse20037 model constructor.
     * @property {module:model/InlineResponse20037}
     */
    InlineResponse20037,

    /**
     * The InlineResponse20038 model constructor.
     * @property {module:model/InlineResponse20038}
     */
    InlineResponse20038,

    /**
     * The InlineResponse20039 model constructor.
     * @property {module:model/InlineResponse20039}
     */
    InlineResponse20039,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse20040 model constructor.
     * @property {module:model/InlineResponse20040}
     */
    InlineResponse20040,

    /**
     * The InlineResponse20041 model constructor.
     * @property {module:model/InlineResponse20041}
     */
    InlineResponse20041,

    /**
     * The InlineResponse20042 model constructor.
     * @property {module:model/InlineResponse20042}
     */
    InlineResponse20042,

    /**
     * The InlineResponse20043 model constructor.
     * @property {module:model/InlineResponse20043}
     */
    InlineResponse20043,

    /**
     * The InlineResponse20044 model constructor.
     * @property {module:model/InlineResponse20044}
     */
    InlineResponse20044,

    /**
     * The InlineResponse20045 model constructor.
     * @property {module:model/InlineResponse20045}
     */
    InlineResponse20045,

    /**
     * The InlineResponse20046 model constructor.
     * @property {module:model/InlineResponse20046}
     */
    InlineResponse20046,

    /**
     * The InlineResponse20047 model constructor.
     * @property {module:model/InlineResponse20047}
     */
    InlineResponse20047,

    /**
     * The InlineResponse20048 model constructor.
     * @property {module:model/InlineResponse20048}
     */
    InlineResponse20048,

    /**
     * The InlineResponse20049 model constructor.
     * @property {module:model/InlineResponse20049}
     */
    InlineResponse20049,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse20050 model constructor.
     * @property {module:model/InlineResponse20050}
     */
    InlineResponse20050,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InstitutionRole model constructor.
     * @property {module:model/InstitutionRole}
     */
    InstitutionRole,

    /**
     * The Job model constructor.
     * @property {module:model/Job}
     */
    Job,

    /**
     * The LTIDomainConfig model constructor.
     * @property {module:model/LTIDomainConfig}
     */
    LTIDomainConfig,

    /**
     * The LTIPlacement model constructor.
     * @property {module:model/LTIPlacement}
     */
    LTIPlacement,

    /**
     * The Link model constructor.
     * @property {module:model/Link}
     */
    Link,

    /**
     * The Locale model constructor.
     * @property {module:model/Locale}
     */
    Locale,

    /**
     * The Locale1 model constructor.
     * @property {module:model/Locale1}
     */
    Locale1,

    /**
     * The Locale2 model constructor.
     * @property {module:model/Locale2}
     */
    Locale2,

    /**
     * The Name model constructor.
     * @property {module:model/Name}
     */
    Name,

    /**
     * The Name1 model constructor.
     * @property {module:model/Name1}
     */
    Name1,

    /**
     * The Node model constructor.
     * @property {module:model/Node}
     */
    Node,

    /**
     * The OAuth2AccessToken model constructor.
     * @property {module:model/OAuth2AccessToken}
     */
    OAuth2AccessToken,

    /**
     * The OAuth2AccessTokenInfo model constructor.
     * @property {module:model/OAuth2AccessTokenInfo}
     */
    OAuth2AccessTokenInfo,

    /**
     * The OAuth2Error model constructor.
     * @property {module:model/OAuth2Error}
     */
    OAuth2Error,

    /**
     * The OriginalityReportingTool model constructor.
     * @property {module:model/OriginalityReportingTool}
     */
    OriginalityReportingTool,

    /**
     * The PagingInfo model constructor.
     * @property {module:model/PagingInfo}
     */
    PagingInfo,

    /**
     * The PrivacyPolicy model constructor.
     * @property {module:model/PrivacyPolicy}
     */
    PrivacyPolicy,

    /**
     * The ProctoringService model constructor.
     * @property {module:model/ProctoringService}
     */
    ProctoringService,

    /**
     * The Question model constructor.
     * @property {module:model/Question}
     */
    Question,

    /**
     * The QuestionHandler model constructor.
     * @property {module:model/QuestionHandler}
     */
    QuestionHandler,

    /**
     * The Resource model constructor.
     * @property {module:model/Resource}
     */
    Resource,

    /**
     * The RestException model constructor.
     * @property {module:model/RestException}
     */
    RestException,

    /**
     * The ReviewStatus model constructor.
     * @property {module:model/ReviewStatus}
     */
    ReviewStatus,

    /**
     * The SISLogEntry model constructor.
     * @property {module:model/SISLogEntry}
     */
    SISLogEntry,

    /**
     * The Score model constructor.
     * @property {module:model/Score}
     */
    Score,

    /**
     * The Score1 model constructor.
     * @property {module:model/Score1}
     */
    Score1,

    /**
     * The Score2 model constructor.
     * @property {module:model/Score2}
     */
    Score2,

    /**
     * The Session model constructor.
     * @property {module:model/Session}
     */
    Session,

    /**
     * The SettingsCopyOptionsV2 model constructor.
     * @property {module:model/SettingsCopyOptionsV2}
     */
    SettingsCopyOptionsV2,

    /**
     * The SignupSheet model constructor.
     * @property {module:model/SignupSheet}
     */
    SignupSheet,

    /**
     * The SystemRole model constructor.
     * @property {module:model/SystemRole}
     */
    SystemRole,

    /**
     * The SystemRoleEnum model constructor.
     * @property {module:model/SystemRoleEnum}
     */
    SystemRoleEnum,

    /**
     * The SystemTask model constructor.
     * @property {module:model/SystemTask}
     */
    SystemTask,

    /**
     * The SystemTaskResult model constructor.
     * @property {module:model/SystemTaskResult}
     */
    SystemTaskResult,

    /**
     * The TargetCourseV2 model constructor.
     * @property {module:model/TargetCourseV2}
     */
    TargetCourseV2,

    /**
     * The Term model constructor.
     * @property {module:model/Term}
     */
    Term,

    /**
     * The UploadedFileInfo model constructor.
     * @property {module:model/UploadedFileInfo}
     */
    UploadedFileInfo,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserMembership model constructor.
     * @property {module:model/UserMembership}
     */
    UserMembership,

    /**
     * The Version model constructor.
     * @property {module:model/Version}
     */
    Version,

    /**
     * The VersionInfo model constructor.
     * @property {module:model/VersionInfo}
     */
    VersionInfo,

    /**
    * The AnnouncementsApi service constructor.
    * @property {module:api/AnnouncementsApi}
    */
    AnnouncementsApi,

    /**
    * The AttendanceApi service constructor.
    * @property {module:api/AttendanceApi}
    */
    AttendanceApi,

    /**
    * The CalendarApi service constructor.
    * @property {module:api/CalendarApi}
    */
    CalendarApi,

    /**
    * The ContentApi service constructor.
    * @property {module:api/ContentApi}
    */
    ContentApi,

    /**
    * The ContentFileAttachmentsApi service constructor.
    * @property {module:api/ContentFileAttachmentsApi}
    */
    ContentFileAttachmentsApi,

    /**
    * The ContentGroupAssignmentsApi service constructor.
    * @property {module:api/ContentGroupAssignmentsApi}
    */
    ContentGroupAssignmentsApi,

    /**
    * The ContentResourcesApi service constructor.
    * @property {module:api/ContentResourcesApi}
    */
    ContentResourcesApi,

    /**
    * The ContentReviewApi service constructor.
    * @property {module:api/ContentReviewApi}
    */
    ContentReviewApi,

    /**
    * The CourseAnnouncementsApi service constructor.
    * @property {module:api/CourseAnnouncementsApi}
    */
    CourseAnnouncementsApi,

    /**
    * The CourseAssessmentsApi service constructor.
    * @property {module:api/CourseAssessmentsApi}
    */
    CourseAssessmentsApi,

    /**
    * The CourseCategoriesApi service constructor.
    * @property {module:api/CourseCategoriesApi}
    */
    CourseCategoriesApi,

    /**
    * The CourseGradeAttemptsApi service constructor.
    * @property {module:api/CourseGradeAttemptsApi}
    */
    CourseGradeAttemptsApi,

    /**
    * The CourseGradeNotationsApi service constructor.
    * @property {module:api/CourseGradeNotationsApi}
    */
    CourseGradeNotationsApi,

    /**
    * The CourseGradebookCategoriesApi service constructor.
    * @property {module:api/CourseGradebookCategoriesApi}
    */
    CourseGradebookCategoriesApi,

    /**
    * The CourseGradesApi service constructor.
    * @property {module:api/CourseGradesApi}
    */
    CourseGradesApi,

    /**
    * The CourseGradingPeriodsApi service constructor.
    * @property {module:api/CourseGradingPeriodsApi}
    */
    CourseGradingPeriodsApi,

    /**
    * The CourseGroupUsersApi service constructor.
    * @property {module:api/CourseGroupUsersApi}
    */
    CourseGroupUsersApi,

    /**
    * The CourseGroupsApi service constructor.
    * @property {module:api/CourseGroupsApi}
    */
    CourseGroupsApi,

    /**
    * The CourseMembershipsApi service constructor.
    * @property {module:api/CourseMembershipsApi}
    */
    CourseMembershipsApi,

    /**
    * The CourseMessagesApi service constructor.
    * @property {module:api/CourseMessagesApi}
    */
    CourseMessagesApi,

    /**
    * The CoursesApi service constructor.
    * @property {module:api/CoursesApi}
    */
    CoursesApi,

    /**
    * The DataSourcesApi service constructor.
    * @property {module:api/DataSourcesApi}
    */
    DataSourcesApi,

    /**
    * The DeprecatedCourseGradesApi service constructor.
    * @property {module:api/DeprecatedCourseGradesApi}
    */
    DeprecatedCourseGradesApi,

    /**
    * The DeprecatedCourseGroupUsersApi service constructor.
    * @property {module:api/DeprecatedCourseGroupUsersApi}
    */
    DeprecatedCourseGroupUsersApi,

    /**
    * The DeprecatedCourseGroupsApi service constructor.
    * @property {module:api/DeprecatedCourseGroupsApi}
    */
    DeprecatedCourseGroupsApi,

    /**
    * The DeprecatedCoursesApi service constructor.
    * @property {module:api/DeprecatedCoursesApi}
    */
    DeprecatedCoursesApi,

    /**
    * The InstitutionalHierarchyApi service constructor.
    * @property {module:api/InstitutionalHierarchyApi}
    */
    InstitutionalHierarchyApi,

    /**
    * The LtiApi service constructor.
    * @property {module:api/LtiApi}
    */
    LtiApi,

    /**
    * The OauthApi service constructor.
    * @property {module:api/OauthApi}
    */
    OauthApi,

    /**
    * The PerformanceDashboardApi service constructor.
    * @property {module:api/PerformanceDashboardApi}
    */
    PerformanceDashboardApi,

    /**
    * The ProctoringApi service constructor.
    * @property {module:api/ProctoringApi}
    */
    ProctoringApi,

    /**
    * The RolesApi service constructor.
    * @property {module:api/RolesApi}
    */
    RolesApi,

    /**
    * The SISLogsApi service constructor.
    * @property {module:api/SISLogsApi}
    */
    SISLogsApi,

    /**
    * The SessionsApi service constructor.
    * @property {module:api/SessionsApi}
    */
    SessionsApi,

    /**
    * The SystemApi service constructor.
    * @property {module:api/SystemApi}
    */
    SystemApi,

    /**
    * The TermsApi service constructor.
    * @property {module:api/TermsApi}
    */
    TermsApi,

    /**
    * The UploadsApi service constructor.
    * @property {module:api/UploadsApi}
    */
    UploadsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
