/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.AnnouncementsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnnouncementsApi', function() {
    describe('learnApiPublicV1AnnouncementsAnnouncementIdDelete', function() {
      it('should call learnApiPublicV1AnnouncementsAnnouncementIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1AnnouncementsAnnouncementIdDelete
        //instance.learnApiPublicV1AnnouncementsAnnouncementIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1AnnouncementsAnnouncementIdGet', function() {
      it('should call learnApiPublicV1AnnouncementsAnnouncementIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1AnnouncementsAnnouncementIdGet
        //instance.learnApiPublicV1AnnouncementsAnnouncementIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1AnnouncementsAnnouncementIdPatch', function() {
      it('should call learnApiPublicV1AnnouncementsAnnouncementIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1AnnouncementsAnnouncementIdPatch
        //instance.learnApiPublicV1AnnouncementsAnnouncementIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1AnnouncementsGet', function() {
      it('should call learnApiPublicV1AnnouncementsGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1AnnouncementsGet
        //instance.learnApiPublicV1AnnouncementsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1AnnouncementsPost', function() {
      it('should call learnApiPublicV1AnnouncementsPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1AnnouncementsPost
        //instance.learnApiPublicV1AnnouncementsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
