/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.ContentFileAttachmentsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContentFileAttachmentsApi', function() {
    describe('learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDelete', function() {
      it('should call learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDelete
        //instance.learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDownloadGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDownloadGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDownloadGet
        //instance.learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdDownloadGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdGet
        //instance.learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsAttachmentIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsGet
        //instance.learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsPost', function() {
      it('should call learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsPost
        //instance.learnApiPublicV1CoursesCourseIdContentsContentIdAttachmentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
