/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.CourseGradingPeriodsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CourseGradingPeriodsApi', function() {
    describe('learnApiPublicV1CoursesCourseIdGradebookPeriodsGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookPeriodsGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookPeriodsGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookPeriodsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdDelete', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdDelete
        //instance.learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdPatch', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdPatch
        //instance.learnApiPublicV1CoursesCourseIdGradebookPeriodsPeriodIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookPeriodsPost', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookPeriodsPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookPeriodsPost
        //instance.learnApiPublicV1CoursesCourseIdGradebookPeriodsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
