/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.DeprecatedCourseGradesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeprecatedCourseGradesApi', function() {
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsAttemptIdGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsAttemptIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsAttemptIdGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsAttemptIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdAttemptsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdDelete', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdDelete
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdPatch', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdPatch
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdPatch', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdPatch
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsColumnIdUsersUserIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookColumnsPost', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookColumnsPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookColumnsPost
        //instance.learnApiPublicV1CoursesCourseIdGradebookColumnsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1CoursesCourseIdGradebookUsersUserIdGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdGradebookUsersUserIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdGradebookUsersUserIdGet
        //instance.learnApiPublicV1CoursesCourseIdGradebookUsersUserIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
