/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.InstitutionalHierarchyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InstitutionalHierarchyApi', function() {
    describe('learnApiPublicV1CoursesCourseIdNodesGet', function() {
      it('should call learnApiPublicV1CoursesCourseIdNodesGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1CoursesCourseIdNodesGet
        //instance.learnApiPublicV1CoursesCourseIdNodesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesGet', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesGet
        //instance.learnApiPublicV1InstitutionalHierarchyNodesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenGet', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenGet
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenPost', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenPost
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdChildrenPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdDelete', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdDelete
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPatch', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPatch
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPut', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPut successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPut
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesCourseIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesGet', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesGet
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdDelete', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdDelete
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdGet', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdGet
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesNodeIdPatch', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesNodeIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesNodeIdPatch
        //instance.learnApiPublicV1InstitutionalHierarchyNodesNodeIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1InstitutionalHierarchyNodesPost', function() {
      it('should call learnApiPublicV1InstitutionalHierarchyNodesPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1InstitutionalHierarchyNodesPost
        //instance.learnApiPublicV1InstitutionalHierarchyNodesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
