/**
 * Learn APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3900.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LearnApIs);
  }
}(this, function(expect, LearnApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LearnApIs.TermsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TermsApi', function() {
    describe('learnApiPublicV1TermsGet', function() {
      it('should call learnApiPublicV1TermsGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1TermsGet
        //instance.learnApiPublicV1TermsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1TermsPost', function() {
      it('should call learnApiPublicV1TermsPost successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1TermsPost
        //instance.learnApiPublicV1TermsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1TermsTermIdDelete', function() {
      it('should call learnApiPublicV1TermsTermIdDelete successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1TermsTermIdDelete
        //instance.learnApiPublicV1TermsTermIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1TermsTermIdGet', function() {
      it('should call learnApiPublicV1TermsTermIdGet successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1TermsTermIdGet
        //instance.learnApiPublicV1TermsTermIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('learnApiPublicV1TermsTermIdPatch', function() {
      it('should call learnApiPublicV1TermsTermIdPatch successfully', function(done) {
        //uncomment below and update the code to test learnApiPublicV1TermsTermIdPatch
        //instance.learnApiPublicV1TermsTermIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
